In [1]:
%pip install tensorflow tensorflow-gpu pandas matplotlib scikit-learn

  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  Running setup.py install for tensorflow-gpu: started
  Running setup.py install for tensorflow-gpu: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-afg3oud4\tensorflow-gpu_1fe6bdc881b54f1387e7e018d90f3c4f\setup.py", line 37, in <module>
          raise Exception(TF_REMOVAL_WARNING)
      Exception:
      
      The "tensorflow-gpu" package has been removed!
      
      Please install "tensorflow" instead.
      
      Other than the name, the two packages have been identical
      since TensorFlow 2.1, or roughly since Sep 2019. For more
      information, see: pypi.org/project/tensorflow-gpu
      
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  error: subprocess-ex

In [2]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np

In [3]:
df = pd.read_csv("C:\\Users\\user\\Desktop\\Python\\Comment Toxicity\\jigsaw-toxic-comment-classification-challenge\\train.csv\\train.csv")

In [4]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [5]:
df.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [6]:
from tensorflow.keras.layers import TextVectorization

In [7]:
df.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [8]:
df['comment_text']

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [9]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [10]:
df = df.head(6000)

In [11]:
x = df['comment_text']
y = df[df.columns[2:]].values

In [12]:
#Preprocessing

In [13]:
MAX_WORDS = 170000 #no of words that will be stored in dictionary as tokens

In [14]:
vectorizer = TextVectorization(max_tokens= MAX_WORDS, output_sequence_length=1800, output_mode= 'int')

In [15]:
x.values

array(["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Best known social networking websites \n\nWhat are the best known social networking websites beside MySpace? 81.223.23.159',
       "Page name \n\nA user has reverted an edit that was going to include a UAV in the list.  The reason stated was that 'A UAV isn't a specific aircraft and the Army isn't part of the RAAF'.  There are quite a

In [16]:
vectorizer.adapt(x.values)

In [17]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'i',
 'a',
 'you',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'with',
 'your',
 'if',
 'was',
 'article',
 'or',
 'but',
 'page',
 'an',
 'my',
 'by',
 'from',
 'do',
 'at',
 'me',
 'so',
 'about',
 'what',
 'can',
 'wikipedia',
 'all',
 'there',
 'has',
 'would',
 'its',
 'will',
 'like',
 'no',
 'one',
 'just',
 'talk',
 'please',
 'they',
 'any',
 'he',
 'we',
 'been',
 'which',
 'dont',
 'here',
 'should',
 'other',
 'more',
 'see',
 'some',
 'his',
 'who',
 'also',
 'im',
 'think',
 'ass',
 'how',
 'because',
 'know',
 'why',
 'out',
 'edit',
 'were',
 'am',
 'fuck',
 'then',
 'people',
 'only',
 'go',
 'up',
 'use',
 'articles',
 'now',
 'hate',
 'their',
 'may',
 'being',
 'when',
 'time',
 'did',
 'than',
 'even',
 'thanks',
 'get',
 'make',
 'information',
 'them',
 'good',
 'well',
 'could',
 'had',
 'yourself',
 'sources',
 'want',
 'very',
 'first',
 'deletion',
 'way',
 'made',

In [18]:
vectorizer("my name is")

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([ 30, 116,   9, ...,   0,   0,   0], dtype=int64)>

In [19]:
vectorizer("what is my name")

<tf.Tensor: shape=(1800,), dtype=int64, numpy=array([38,  9, 30, ...,  0,  0,  0], dtype=int64)>

In [20]:
vectorized_text = vectorizer(x.values)

In [21]:
vectorized_text

<tf.Tensor: shape=(6000, 1800), dtype=int64, numpy=
array([[  638,    75,     2, ...,     0,     0,     0],
       [26444,    55,  1842, ...,     0,     0,     0],
       [  484,   418,    69, ...,     0,     0,     0],
       ...,
       [  234,   458,   953, ...,     0,     0,     0],
       [   28,   116,     7, ...,     0,     0,     0],
       [17302,   145,  2151, ...,     0,     0,     0]], dtype=int64)>

In [22]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [23]:
batch_x, batch_y = dataset.as_numpy_iterator().next()

In [24]:
batch_x.shape


(16, 1800)

In [25]:
batch_y.shape

(16, 6)

In [26]:
len(dataset) #this number is in batches of 16, meaning the acual lenght is 9974*16

375

In [27]:
train = dataset.take(int(len(dataset)*.7))
val = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [28]:
print(len(train))
print(len(val))
print(len(test))

262
75
37


In [29]:
train.as_numpy_iterator().next()  #next() cuz of 1 batch of 16 examples

(array([[ 4132, 24519,     9, ...,     0,     0,     0],
        [24774,   283,   791, ...,     0,     0,     0],
        [    2,  1054,    10, ...,     0,     0,     0],
        ...,
        [   14,    28,    61, ...,     0,     0,     0],
        [  465, 16226,  1983, ...,     0,     0,     0],
        [   75,     9,    12, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [30]:
#Creating the Sequential Model now

In [31]:
from keras.models import Sequential
from keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [32]:
model = Sequential()
#Embedding layer, where integer indices representing tokens are mapped to vectors of fixed sized, aka word embeddings
model.add(Embedding(MAX_WORDS+1,32 ))
#Bidirectional layer because words that came before the current word can change the meaning of the given sentence, tanh cuz lstm
model.add(Bidirectional(LSTM(32, activation='tanh')))
#Features are extracted here
model.add(Dense(128, activation= 'relu'))
model.add(Dense(256, activation= 'relu'))
model.add(Dense(128, activation= 'relu'))
#Final layer
model.add(Dense(6, activation= 'sigmoid'))

In [33]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [34]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [35]:
history = model.fit(train, epochs=5, validation_data=val)

Epoch 1/5
262/262 ━━━━━━━━━━━━━━━━━━━━ 267s 991ms/step - accuracy: 0.6933 - loss: 0.2294 - val_accuracy: 0.9967 - val_loss: 0.0816
Epoch 2/5
262/262 ━━━━━━━━━━━━━━━━━━━━ 251s 957ms/step - accuracy: 0.9913 - loss: 0.0787 - val_accuracy: 0.9950 - val_loss: 0.0560
Epoch 3/5
262/262 ━━━━━━━━━━━━━━━━━━━━ 255s 974ms/step - accuracy: 0.9927 - loss: 0.0581 - val_accuracy: 0.9942 - val_loss: 0.0455
Epoch 4/5
262/262 ━━━━━━━━━━━━━━━━━━━━ 265s 1s/step - accuracy: 0.9109 - loss: 0.0485 - val_accuracy: 0.9917 - val_loss: 0.0370
Epoch 5/5
262/262 ━━━━━━━━━━━━━━━━━━━━ 258s 983ms/step - accuracy: 0.8848 - loss: 0.0396 - val_accuracy: 0.9925 - val_loss: 0.0381


In [36]:
#Evaluation

In [41]:
from tensorflow.python.keras.metrics import Precision, Recall, CategoricalAccuracy

In [42]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [43]:
for batch in test.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch
    # Make a prediction 
    yhat = model.predict(X_true)
    
    # Flatten the predictions
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true, yhat)
    re.update_state(y_true, yhat)
    acc.update_state(y_true, yhat)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 185ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 175ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 

In [44]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8440366983413696, Recall:0.8288288116455078, Accuracy:0.6216216087341309
